stop-words = "lemur-stopwords.txt"
prefix = "."
query-judgements = "cranfield/cranfield-qrels.txt"
index = "cranfield-idx"
corpus = "tutorial.toml"
dataset = "cranfield"
[[analyzers]]
	filter = "default-unigram-chain"
	ngram = 1
	method = "ngram-word"
